# .drone.yml

kind: pipeline
type: docker
name: default


trigger:
  event:
    - push
    - pull_request
  path:
    include:
      - install/auto/* 

steps:
- name: build
  image: nixos/nix
  commands:
    - cp install/auto/default.nix .
    - cp install/auto/configuration.nix .
    - cp install/auto/hardware-configuration.nix .
    - nix-build
    - scp result/iso/*.iso root@172.30.100.76:/tmp/

- name: notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 1008599816563064873
    webhook_token: ZfHVejau6_fSxxOWHI-kMGLgy1ZHMwWQSjmiLOqGxFPjtrLQ3gxuxf8ea37wPzKYTMnP
    message: >
       📝 {{repo.name}} / {{commit.branch}} - {{commit.message}}
       {{#success build.status}}
         ✅ succeeded  for 👷‍♂️ build {{build.number}}
       {{else}}
         🛑 failed for 👷‍♂️ build {{build.number}}
       {{/success}}       
  when:
    status:
      - failure
      - success

trigger:
  event:
    - promote
    - push
    - pull_request